version: "3.5"
services:
  chat_app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3032:3032"
    depends_on:
      - db_service
      - redis_service
    environment:
      - DB_URL=mongodb://db_service
      - REDIS_URL=redis://redis_service:6379
      - REDIS_HOST=redis_service
      - REDIS_PORT=6379
    networks:
      - chat_app_net

  db_service:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - chat_app_net

  redis_service:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - chat_app_net

networks:
  chat_app_net:

volumes:
  mongodata: