version: "3"
services:
  chat_app:
    depends_on:
      - db
      - redis
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3032:3032"
    environment:
      - DB_URL=mongodb://db_mongo
      - REDIS_URL=redis://redis_hostname:6379

  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis_hostname
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    volumes:
      - redisdata:/data/redis
    ports:
      - '6379:6379'

volumes:
  mongodata:
  redisdata: