export enum ErrorMessage {
  INVALID_APP_MODE = 'INVALID_APP_MODE',
  UNEXPECTED = 'UNEXPECTED',
  ERROR_CHECK_TYPE = 'ERROR_CHECK_TYPE',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  JWT_USER_GUARD_CAN_NOT_BE_INSTANTIATED = 'JWT_USER_GUARD_CAN_NOT_BE_INSTANTIATED',
  YOU_MUST_LOGIN = 'YOU_MUST_LOGIN'
}